//
//  ViewTasksInteractor.swift
//  Task Magician
//
//  Created by Сергей Павленок on 13.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewTasksBusinessLogic
{
  func doSomething(request: ViewTasks.Something.Request)
}

protocol ViewTasksDataStore
{
  //var name: String { get set }
}

class ViewTasksInteractor: ViewTasksBusinessLogic, ViewTasksDataStore {
  var presenter: ViewTasksPresentationLogic?
  var worker: ViewTasksWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ViewTasks.Something.Request)
  {
    worker = ViewTasksWorker()
    worker?.doSomeWork()
    
    let response = ViewTasks.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
