//
//  ViewTasksModels.swift
//  Task Magician
//
//  Created by Сергей Павленок on 13.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ViewTasks
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request { }
    struct Response { }
    struct ViewModel { }
  }
    enum GetUserInfo
    {
        struct Request {
            enum RequestType {
                case getUser
            }
        }
        struct Response {
            enum ResponseType {
                case presentUserInfo(user: UserResponse?)
            }
        }
        struct ViewModel {
            enum ViewModelData {
                case displayUser(userViewModel: UserViewModel)
            }
        }
    }
}

struct UserViewModel: TitleViewViewModel {
    var photoUrlString: String?
    var name: String
}
